# Generated by Django 3.1.5 on 2021-09-05 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/ads')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='uploads/brands')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmname', models.CharField(max_length=300)),
                ('gstin', models.CharField(max_length=300, unique=True)),
                ('ownername', models.CharField(max_length=200)),
                ('contact', models.PositiveIntegerField(default=91)),
                ('ownerphoto', models.ImageField(upload_to='uploads/owners')),
                ('firmphoto', models.ImageField(upload_to='uploads/firms')),
                ('billphoto', models.ImageField(upload_to='uploads/bills')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(default='mart', max_length=200)),
                ('jd', models.TextField(default='', max_length=5000)),
                ('contact', models.PositiveIntegerField(default=7375865792)),
                ('mail', models.EmailField(default='amanvyas200@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='uploads/carouselimages')),
                ('image2', models.ImageField(default='', upload_to='uploads/carouselimages')),
                ('image3', models.ImageField(default='', upload_to='uploads/carouselimages')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='martapp.category')),
            ],
            options={
                'verbose_name_plural': 'childcategories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
                ('message', models.TextField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], max_length=200)),
                ('orderid', models.CharField(default='', max_length=300)),
                ('paymentid', models.CharField(default='', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(max_length=255)),
                ('image1', models.ImageField(upload_to='uploads/products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='uploads/products')),
                ('price', models.PositiveIntegerField(default=0)),
                ('minimumquantity', models.PositiveIntegerField(default=10)),
                ('pricefor', models.CharField(default='', max_length=300)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('business', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='martapp.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='martapp.category')),
                ('childcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='martapp.childcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Userproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('orderid', models.CharField(default='', max_length=200)),
                ('paymentid', models.CharField(default='', max_length=200)),
                ('totalprice', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('on the way', 'on the way'), ('delievered', 'delievered')], default='Accepted', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='martapp.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='martapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField(default='')),
                ('address', models.TextField(max_length=2000)),
                ('city', models.CharField(max_length=300)),
                ('pincode', models.IntegerField(default='')),
                ('state', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='martapp.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
