# Generated by Django 3.1.5 on 2021-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.AddField(
            model_name='product',
            name='firmname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='gstin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
