# Generated by Django 3.1.5 on 2021-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0004_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('under review', 'under review'), ('onboarded', 'onboarded')], default='under review', max_length=100),
        ),
    ]
