# Generated by Django 3.1.5 on 2021-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0005_auto_20210906_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('under review', 'under review'), (' Congratulations,onboarded', 'onboarded')], default='under review', max_length=100),
        ),
    ]
