# Generated by Django 3.1.5 on 2021-09-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0007_userproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
