# Generated by Django 3.1.5 on 2021-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martapp', '0008_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
